version: '3.8'
services:
  web:
    build: .
    # command: 'cd backend && npm run start'
    # volumes:
    #  - .:/usr/app
    ports:
     - "3000:3000"
     - "3001:3001"
    depends_on:
      db-dev:
        condition: service_healthy

  db-dev:
    image: postgres:14.2
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=nest
     - PGUSER=postgres
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
