export {default as Logo42} from "./images/42logo.svg"
export {default as Logo1337} from "./images/1337logo.svg"
export {default as DefaultGame} from "./images/defaultgame.png"
export {default as UltimateGame} from "./images/ultimategame.png"
export {default as LiveGames} from "./images/livegames.png"
export {default as BgVectors} from "./images/bgvectors.png"
export {default as ChatHomeVector} from "./images/chathome.svg"
export {default as NotFound404} from "./images/404.svg"
